name: Playtest Bug Report
description: Report issues found in the playtest build
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      placeholder: What went wrong?
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: Windows 11 / macOS 13 / Ubuntu 22.04
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: Your graphics card model
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Start the game
        2. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Attach files from playtest_reports/
