name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}"
          restore-keys: ${{ runner.os }}-pip-
      - name: Install
        run: |
          pip install pygame~=2.5.2 --only-binary=:all:
          pip install -e .[dev,graphics]
      - name: Lint
        run: |
          ruff check super_pole_position tests
          mypy --strict super_pole_position || true
      - name: Test
        run: pytest --cov=super_pole_position
      - name: Parity Audit (non-strict)
        run: python tools/parity_audit.py --seed 42 --frames 200 --audio 5 --dump build/parity_run.json
        continue-on-error: true

  ai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: "${{ runner.os }}-pip-ai-${{ hashFiles('requirements.txt') }}"
          restore-keys: ${{ runner.os }}-pip-ai-
      - name: Install AI extras
        run: |
          pip install pygame~=2.5.2 --only-binary=:all:
          pip install -e .[dev,ai,graphics]
      - name: Lint
        run: |
          ruff check super_pole_position tests
          mypy --strict super_pole_position || true
      - name: Test
        run: pytest --cov=super_pole_position

  playtest-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip install build
          python -m build
      - name: Playtest install check
        run: |
          python -m pip install dist/*whl
          pole-position --release --headless --steps 120 --seed 7

